#!/bin/sh
#/**
#  * <div class="p">
#  * 'Controller' script for the <a
#  *   href="http://dogfoodsoftware.com/documentation/conveyor/ref/Branching-Strategy">Conveyor
#  *   branch strategy</a> extensions. Please refer to the branch strategy
#  *   documentation for details on usage.
#  * </div>
#  * <div id="Implementation" data-perspective="implementation" class="grid_12 blurbSummary">
#  *   <div class="blurbTitle">Implementation</div>
#  *   <div class="p">
#  *     This script essentially reads the first argument&mdash;which is
#  *     understood as the resource name&mdash;and then looks for the matching
#  *     <code>git-conveyor-*</code> script to handle the resource action.
#  *   </div>
#  *   <div class="subHeader"><span>Platform Workarounds</span></div>
#  *   <div class="p">
#  *     Thanks to <a href=""></a> <a
#  *     href="https://github.com/nvie/gitflow">GitFlow</a> for these
#  *     workarounds. If you don't like our approach to branch management,
#  *     GitFlow offers a great alternative.
#  *   </div>
#  */

# If in future versions, we want to use shFlags for commandline option
# processing, we will want to set this variable, used by shFlags for
# compatibility purposes. As we don't currently do any option processing, it
# is not necessary.
# if uname -s | egrep -iq 'bsd'; then export EXPR_COMPAT=1; fi

source "$HOME/.conveyor/config"
CONVEYOR_WORKFLOW_RUNNABLE="$CONVEYOR_HOME/workflow/runnable"

source "$CONVEYOR_WORKFLOW_RUNNABLE/lib/shflags"
source "$CONVEYOR_WORKFLOW_RUNNABLE/lib/resty"
source "$CONVEYOR_WORKFLOW_RUNNABLE/lib/rest-lib.sh"
source "$CONVEYOR_WORKFLOW_RUNNABLE/common-checks.sh"
source "$CONVEYOR_WORKFLOW_RUNNABLE/common-lib.sh"
source "$CONVEYOR_WORKFLOW_RUNNABLE/lib/help.sh"

RESOURCE="$1"; shift

source "$CONVEYOR_WORKFLOW_RUNNABLE/git-conveyor-$RESOURCE"

resource_do "$@"
#/**
#  * </div><!-- #Implementation.blurbSummary -->
#  */
